const data = {
  product: [
    {
      _id: '1',
      name: 'Nike Air Max: Unlimited Edition',
      slug: 'nike-air-max-unlimited-edition',
      category: 'Shoes',
      image: '/images/p1.webp',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReview: 10,
      description: 'Medium Quality ',
    },
    {
      _id: '2',
      name: 'Nike Air Max: limited Edition',
      slug: 'nike-air-max-limited-edition',
      category: 'Shoes',
      image: '/images/p1.webp',
      price: 190,
      countInStock: 2,
      brand: 'Nike',
      rating: 5,
      numReview: 1,
      description: 'High quality shoes',
    },
    {
      name: 'Adidas Stan Smith : Corea Edition',
      slug: 'adidas-stan-smith-corea-edition',
      category: 'Shoes',
      image: '/images/p2.webp',
      price: 190,
      countInStock: 0,
      brand: 'Nike',
      rating: 3.5,
      numReview: 1,
      description: "Shoes for hypster i doesn't want this in my house",
    },
    {
      name: 'Adidas Stan Smith : Corea2 Edition',
      slug: 'adidas-stan-smith-corea-2-edition',
      category: 'Shoes',
      image: '/images/p2.webp',
      price: 190,
      countInStock: 0,
      brand: 'Nike',
      rating: 3.5,
      numReview: 1,
      description: "Shoes for hypster i doesn't want this in my house",
    },
  ],
};

export default data;
